import AppKit
import Foundation

let root = URL(fileURLWithPath: CommandLine.arguments[1], isDirectory: true)
let W: CGFloat = 1920, H: CGFloat = 1080
struct Scene { let label: String; let title: String; let caption: String; let boxes: [(String,String,String)] }
let topics: [(String, NSColor, [Scene])] = [
 ("pre-training", NSColor(calibratedRed: 0.35, green: 0.82, blue: 1, alpha: 1), [
  Scene(label:"01 · DEFINITION", title:"PRE-TRAINING", caption:"Broad data teaches general patterns before task-specific adaptation.", boxes:[("BROAD DATA","text · code · images","many examples"), ("TRAINING","predict and compare","learn patterns"), ("BASE MODEL","reusable starting point","ready to adapt")]),
  Scene(label:"02 · ANALOGY", title:"GENERAL EDUCATION FIRST", caption:"A student studies many subjects before choosing one job.", boxes:[("MANY SUBJECTS","broad material","learn widely"), ("PRACTICE","repeat predictions","improve gradually"), ("SPECIALIST LATER","adapt the base","focus the role")]),
  Scene(label:"03 · PROCESS", title:"PREDICT → COMPARE → UPDATE", caption:"Prediction errors update parameters across repeated examples.", boxes:[("TOKENS","make units","model input"), ("PREDICT","guess next part","a continuation"), ("ERROR","compare target","measure"), ("UPDATE","adjust values","repeat")]),
  Scene(label:"04 · EXAMPLE", title:"THE TRADER CLOSED...", caption:"A language model learns from likely continuations such as “risky.”", boxes:[("INPUT","The trader closed the position because it was","partial sentence"), ("PREDICT","likely next tokens","score candidates"), ("OUTPUT","risky","one continuation")]),
  Scene(label:"05 · BOUNDARY", title:"NOT PROMPTING OR RAG", caption:"Pre-training changes parameters; prompting instructs at runtime; RAG retrieves outside information.", boxes:[("PRE-TRAINING","broad initial training","changes parameters"), ("PROMPTING","runtime instructions","no retraining"), ("RAG","outside information","retrieval at query time")]),
  Scene(label:"06 · REMEMBER", title:"A BROAD STARTING POINT", caption:"Pre-training teaches broad patterns before task-specific adaptation.", boxes:[("BROAD DATA","general patterns","learn"), ("BASE MODEL","capability","save"), ("ADAPTATION","application task","later")])
 ]),
 ("fine-tuning", NSColor(calibratedRed: 1, green: 0.65, blue: 0.35, alpha: 1), [
  Scene(label:"01 · DEFINITION", title:"FINE-TUNING", caption:"Additional training adapts a pre-trained model for a narrower behavior or task.", boxes:[("BASE MODEL","broad skills","start here"), ("FOCUSED DATA","target examples","show desired behavior"), ("SPECIALIZED MODEL","more consistent","task or style")]),
  Scene(label:"02 · ANALOGY", title:"SPECIALIST TRAINING", caption:"Keep broad skills, then practice a narrower job with focused examples.", boxes:[("GENERAL EDUCATION","broad capability","already learned"), ("SPECIALIST COURSE","focused practice","target behavior"), ("TARGET ROLE","consistent output","use")]),
  Scene(label:"03 · PROCESS", title:"START → TRAIN → EVALUATE", caption:"A base model learns from target examples, then tests check the trade-offs.", boxes:[("BASE MODEL","load it","broad skills"), ("EXAMPLES","input + output","desired format"), ("UPDATE","parameters or adapters","additional training"), ("EVALUATE","quality and regressions","check")]),
  Scene(label:"04 · EXAMPLES", title:"THREE TARGET BEHAVIORS", caption:"Focused examples can shape classification, writing style, or structured output.", boxes:[("SUPPORT","customer ticket","consistent category"), ("STYLE","draft request","preferred tone"), ("SCHEMA","document","predictable fields")]),
  Scene(label:"05 · BOUNDARY", title:"NOT PROMPTING OR RAG", caption:"Fine-tuning changes learned behavior; prompting changes instructions; RAG retrieves at query time.", boxes:[("FINE-TUNING","additional training","changes behavior"), ("PROMPTING","runtime input","no retraining"), ("RAG","external information","retrieval")]),
  Scene(label:"06 · REMEMBER", title:"ADAPT BEHAVIOR, NOT LIVE FACTS", caption:"Fine-tuning makes a pre-trained model more consistent for a specific task; it is not a live knowledge update.", boxes:[("PRE-TRAINED","broad model","starting point"), ("FOCUSED EXAMPLES","target behavior","adapt"), ("EVALUATION","check regressions","keep fit")])
 ])
]
func fill(_ r:NSRect,_ c:NSColor,_ rad:CGFloat=0){c.setFill(); (rad > 0 ? NSBezierPath(roundedRect:r,xRadius:rad,yRadius:rad) : NSBezierPath(rect:r)).fill()}
func text(_ s:String,_ x:CGFloat,_ top:CGFloat,_ size:CGFloat,_ c:NSColor,_ w:NSFont.Weight = .regular,_ width:CGFloat = 1600){NSString(string:s).draw(in:NSRect(x:x,y:H-top-size*1.38,width:width,height:size*1.7),withAttributes:[.font:NSFont.systemFont(ofSize:size,weight:w),.foregroundColor:c])}
for (slug, accent, scenes) in topics { let dir=root.appendingPathComponent(slug); try? FileManager.default.createDirectory(at:dir,withIntermediateDirectories:true); for (i,scene) in scenes.enumerated(){ let im=NSImage(size:NSSize(width:W,height:H)); im.lockFocus(); fill(NSRect(x:0,y:0,width:W,height:H),NSColor(calibratedRed:0.027,green:0.063,blue:0.098,alpha:1)); fill(NSRect(x:92,y:132,width:8,height:790),accent); text("REBECCA LI  /  MODULE 04",130,74,20,.lightGray,.medium); text(scene.label,130,126,19,accent,.bold); text(scene.title,130,166,scene.title.count>25 ? 48:64,.white,.bold); let gap:CGFloat=30; let bw=(1680-gap*CGFloat(scene.boxes.count-1))/CGFloat(scene.boxes.count); for (j,b) in scene.boxes.enumerated(){let x=120+CGFloat(j)*(bw+gap); let r=NSRect(x:x,y:390,width:bw,height:190); fill(r,NSColor(calibratedRed:0.055,green:0.13,blue:0.20,alpha:0.98),20); accent.setStroke(); let p=NSBezierPath(roundedRect:r,xRadius:20,yRadius:20); p.lineWidth=2;p.stroke(); text(b.0,x+24,414,18,accent,.bold,bw-48); text(b.1,x+24,462,bw>400 ? 27:22,.white,.semibold,bw-48); text(b.2,x+24,530,19,.lightGray,.regular,bw-48) }; fill(NSRect(x:120,y:70,width:1680,height:4),NSColor(calibratedWhite:0.18,alpha:1)); fill(NSRect(x:120,y:70,width:CGFloat(i+1)*280,height:4),accent); fill(NSRect(x:120,y:18,width:1680,height:104),NSColor(calibratedRed:0.02,green:0.045,blue:0.07,alpha:0.98),16); text(scene.caption,155,1015,23,.white,.medium,1580); im.unlockFocus(); let cg=im.cgImage(forProposedRect:nil,context:nil,hints:nil)!; try? NSBitmapImageRep(cgImage:cg).representation(using:.png,properties:[:])!.write(to:dir.appendingPathComponent(String(format:"scene-%02d.png",i))) } }
