(function(){document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="software-roadmap.css">');
const links=['how-software-works','frontend-browser','http-apis','backend','module-05','authentication-security','system-architecture','development-git','cloud-deployment','testing-observability'];
const modules=[['How Software Works','Understand the complete path from user action to system response.',['Software','Client','Frontend','Backend','API','Database']],['Frontend & Browser','Understand what runs in the browser and how users interact with web pages.',['Browser','HTML','CSS','JavaScript','DOM','Event']],['HTTP & APIs','Understand how software systems communicate through requests and responses.',['HTTP','HTTPS','URL','API','Endpoint','Request']],['Backend','Understand what happens after a request reaches the server.',['Backend','Server','Python','Framework','Validation','Business Logic','Configuration']],['Database & SQL','Understand how application data is stored, organized, queried, and changed.',['Database','Table','Row','Schema','Primary Key','Foreign Key','SQL']],['Authentication & Security','Understand identity, permissions, tokens, and system access.',['Authentication','Authorization','Session','Token','JWT','SSO','Role','Permission','RBAC','API Key','Secret','Encryption','Hashing','CORS','CSRF','XSS']],['System Architecture','Understand how services and infrastructure components fit together.',['Architecture','Service','Monolith','API Gateway','Cache','Message Queue']],['Development & Git','Understand how source code is managed, reviewed, merged, and released.',['Source Code','Repository','Git','Commit','Branch','Main','Pull Request','Merge','Version','Release','Build']],['Cloud & Deployment','Understand how software moves from source code to a live environment.',['Cloud','Hosting','Deployment','Domain','Docker','CI/CD']],['Testing & Observability','Understand how software is tested, monitored, and investigated.',['Testing','Unit Test','Integration Test','E2E Test','Monitoring','Observability']]];
const arrowFlow=(items)=>items.map((x,i)=>`<div>${x}</div>${i<items.length-1?'<i>→</i>':''}`).join('');document.querySelector('[data-flow="run"]').innerHTML=arrowFlow(['User','Browser / App','Frontend','HTTP / API','Backend','Business Logic','Database','Response','Frontend Update']);document.querySelector('[data-flow="build"]').innerHTML=arrowFlow(['Code','Git','Test','Build','Deploy','Production','Monitor']);document.querySelector('[data-flow="save"]').innerHTML=arrowFlow(['HTML Button','JavaScript','POST API','Backend','SQL INSERT','Database','JSON Response']);
const stacked=(items)=>items.map((x,i)=>`<div>${x}</div>${i<items.length-1?'<i>↓</i>':''}`).join('');document.querySelector('[data-map="runtime"]').innerHTML=stacked(['User','01 · How Software Works','02 · Frontend & Browser','03 · HTTP & APIs','04 · Backend','05 · Database & SQL']);document.querySelector('[data-map="delivery"]').innerHTML=stacked(['08 · Development & Git','09 · Cloud & Deployment','10 · Testing & Observability']);
 document.querySelector('[data-modules]').innerHTML=modules.map((m,i)=>{const href=i===2?'http-apis.html':i===3?'backend-overview.html':i===4?'module-05.html':i===5?'module-06.html':i===7?'module-08.html':`knowledge-placeholder.html?type=software&title=${encodeURIComponent(m[0]+' Glossary')}`;const topics=m[2].map(topic=>topic==='Source Code'?'<a href="source-code.html">Source Code</a>':topic==='Repository'?'<a href="repository.html">Repository</a>':topic==='Schema'?'<a href="schema.html">Schema</a>':topic==='Merge'?'<a href="merge.html">Merge</a>':topic==='Main'?'<a href="main.html">Main</a>':topic==='Git'?'<a href="git.html">Git</a>':topic==='Commit'?'<a href="commit.html">Commit</a>':topic==='Branch'?'<a href="branch.html">Branch</a>':topic==='Pull Request'?'<a href="pull-request.html">Pull Request</a>':topic==='Version'?'<a href="version.html">Version</a>':topic==='Release'?'<a href="release.html">Release</a>':topic==='Build'?'<a href="build.html">Build</a>':topic).join(' · ');return `<a class="roadmap-card" href="${href}"><span class="card-number">${String(i+1).padStart(2,'0')}</span><h3>${m[0].toUpperCase()}</h3><p>${m[1]}</p><b>KEY TOPICS</b><div class="topics">${topics}</div><em>Open Module →</em></a>`}).join('');
const flows=['Load a Web Page','Save Data','Login','Search','Create Order','Update Data','Delete Data','Upload File','Download / Export','Approval Workflow','Payment','Notification','Webhook','Batch / Scheduled Job','Async Processing'];document.querySelector('[data-real-flows]').innerHTML=flows.map(x=>`<a href="${x==='Login'?'login.html':`knowledge-placeholder.html?type=software&title=${encodeURIComponent(x)}`}"><b>${x}</b><span>Open Flow →</span></a>`).join('');document.querySelector('[data-learning-path]').innerHTML=modules.map((m,i)=>{const href=i===2?'http-apis.html':i===3?'backend-overview.html':i===4?'module-05.html':i===5?'authentication-security.html':`knowledge-placeholder.html?type=software&title=${encodeURIComponent(m[0]+' Glossary')}`;return `<a href="${href}">${String(i+1).padStart(2,'0')} ${m[0]}</a>`}).join('<i>→</i>')+'<i>→</i><a href="#real-system-flows">Real System Flows</a>';
document.querySelectorAll('[data-modules] .roadmap-card')[5]?.setAttribute('href','module-06.html');
document.querySelectorAll('[data-learning-path] a')[5]?.setAttribute('href','module-06.html');
const learningPath=document.querySelector('[data-learning-path]'); if(learningPath) learningPath.querySelectorAll('a').forEach((link)=>{if(link.textContent.includes('Authentication & Security')) link.href='module-06.html';});
})();
document.querySelectorAll('[data-learning-path] a[href="authentication-security.html"]').forEach((link) => { link.href = 'module-06.html'; });
document.querySelectorAll('[data-modules] .roadmap-card')[4]?.setAttribute('href', 'module-05.html');
document.querySelectorAll('[data-learning-path] a')[4]?.setAttribute('href', 'module-05.html');
document.querySelectorAll('[data-modules] .roadmap-card').forEach((link) => { if (link.querySelector('h3')?.textContent.trim() === 'DEVELOPMENT & GIT') link.href = 'module-08.html'; });
document.querySelectorAll('[data-learning-path] a').forEach((link) => { if (link.textContent.includes('Development & Git')) link.href = 'module-08.html'; });
document.querySelectorAll('[data-learning-path] a')[7]?.setAttribute('href','module-08.html');
document.querySelectorAll('[data-modules] .roadmap-card').forEach((card) => {
  if (card.querySelector('h3')?.textContent.trim() === 'DEVELOPMENT & GIT') {
    const topics = card.querySelector('.topics');
    if (topics && !topics.querySelector('a[href="github.html"]')) {
      topics.innerHTML = topics.innerHTML.replace('Git ·', 'Git · <a href="github.html">GitHub</a> ·');
    }
    if (topics && !topics.querySelector('a[href="code-review.html"]')) {
      topics.innerHTML += ' · <a href="code-review.html">Code Review</a>';
    }
  }
});
